import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {SidebarProvider} from "@/components/ui/sidebar"
import {AppSidebar} from "@/components/app-sidebar/app-sidebar"
import {Header} from "@/components/core/header";
import {Footer} from "@/components/core/footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body>
		<SidebarProvider>
			<AppSidebar/>
			<div className={"flex flex-col w-full h-auto "}>
				<Header/>
				<main
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					{children}
				</main>
				<Footer/>
			</div>
		</SidebarProvider>
		</body>
		</html>
	);
}
